name: nextstrain
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - augur=13.0.0
  - epiweeks=2.1.2
  - iqtree=2.1.2
  - mafft=7.475
  - python>=3.7*
  - pip>=21.1.1
  - seaborn>=0.11*
  - pip:
    - rethinkdb==2.3.0.post6
