clade_repo: "https://raw.githubusercontent.com/influenza-clade-nomenclature/"
dataset_repo: "https://raw.githubusercontent.com/nextstrain/nextclade_data/release/data/nextstrain/flu"

changelog: "- addition of trees to datasets for internal segments of Influenza A and B viruses"


builds:
  h1n1pdm:
    pb2:
      root: "A/California/7/2009"
      refs:
        NC_026438:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pb1:
      root: "A/California/7/2009"
      refs:
        NC_026435:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pa:
      root: "A/California/7/2009"
      refs:
        NC_026437:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 1800 --subsample-max-sequences 200"
    np:
      root: "A/California/7/2009"
      refs:
        NC_026436:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 1200 --subsample-max-sequences 200"
    mp:
      root: "A/California/7/2009"
      refs:
        NC_026431:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
    ns:
      root: "A/California/7/2009"
      refs:
        NC_026432:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
  h3n2:
    pb2:
      root: "A/HongKong/1/1968"
      refs:
        NC_007373:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pb1:
      root: "A/HongKong/1/1968"
      refs:
        NC_007372:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pa:
      root: "A/HongKong/1/1968"
      refs:
        NC_007371:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 1800 --subsample-max-sequences 200"
    np:
      root: "A/HongKong/1/1968"
      refs:
        NC_007369:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 1200 --subsample-max-sequences 200"
    mp:
      root: "A/HongKong/1/1968"
      refs:
        NC_007367:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
    ns:
      root: "A/HongKong/1/1968"
      refs:
        NC_007370:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
  b:
    pb2:
      root: "B/Lee/1940"
      refs:
        CY115158:
          reference_strain: B/Brisbane/60/2008
          filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pb1:
      root: "B/Lee/1940"
      refs:
        CY115157:
          reference_strain: B/Brisbane/60/2008
          filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pa:
      root: "B/Lee/1940"
      refs:
        CY115156:
          reference_strain: B/Brisbane/60/2008
          filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 1800 --subsample-max-sequences 200"
    np:
      root: "B/Lee/1940"
      refs:
        CY115154:
          reference_strain: B/Brisbane/60/2008
          filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 1200 --subsample-max-sequences 200"
    mp:
      root: "B/Lee/1940"
      refs:
        CY115152:
          reference_strain: B/Brisbane/60/2008
          filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
    ns:
      root: "B/Lee/1940"
      refs:
        CY115155:
          reference_strain: B/Brisbane/60/2008
          filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 600 --subsample-max-sequences 200"
  h2n2:
    pb2:
      root: "A/Albany/26/1957"
      refs:
        NC_007378:
          reference_strain: A/Korea/426/1968
          filter: "--min-date 1957 --max-date 1969 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pb1:
      root: "A/Albany/26/1957"
      refs:
        NC_007375:
          reference_strain: A/Korea/426/1968
          filter: "--min-date 1957 --max-date 1969 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pa:
      root: "A/Albany/26/1957"
      refs:
        NC_007376:
          reference_strain: A/Korea/426/1968
          filter: "--min-date 1957 --max-date 1969 --probabilistic-sampling --group-by year region --min-length 1800 --subsample-max-sequences 200"
    ha:
      root: "A/Albany/26/1957"
      refs:
        NC_007374:
          reference_strain: A/Korea/426/1968
          filter: "--min-date 1957 --max-date 1969 --probabilistic-sampling --group-by year region --min-length 1300 --subsample-max-sequences 200"
    np:
      root: "A/Albany/26/1957"
      refs:
        NC_007381:
          reference_strain: A/Korea/426/1968
          filter: "--min-date 1957 --max-date 1969 --probabilistic-sampling --group-by year region --min-length 1200 --subsample-max-sequences 200"
    na:
      root: "A/Albany/26/1957"
      refs:
        NC_007382:
          reference_strain: A/Korea/426/1968
          filter: "--min-date 1957 --max-date 1969 --probabilistic-sampling --group-by year region --min-length 1200 --subsample-max-sequences 200"
    mp:
      root: "A/Albany/26/1957"
      refs:
        NC_007377:
          reference_strain: A/Korea/426/1968
          filter: "--min-date 1957 --max-date 1969 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
    ns:
      root: "A/Albany/26/1957"
      refs:
        NC_007380:
          reference_strain: A/Korea/426/1968
          filter: "--min-date 1957 --max-date 1969 --probabilistic-sampling --group-by year region --min-length 600 --subsample-max-sequences 200"
