clade_repo: "https://raw.githubusercontent.com/influenza-clade-nomenclature/"
dataset_repo: "https://raw.githubusercontent.com/nextstrain/nextclade_data/release/data/nextstrain/flu"

changelog: "- addition of trees to datasets for internal segments of Influenza A and B viruses"


builds:
  h1n1pdm:
    pb2:
      root: "A/California/7/2009"
      refs:
        NC_026438:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pb1:
      root: "A/California/7/2009"
      refs:
        NC_026435:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pa:
      root: "A/California/7/2009"
      refs:
        NC_026437:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 1800 --subsample-max-sequences 200"
    np:
      root: "A/California/7/2009"
      refs:
        NC_026436:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 1200 --subsample-max-sequences 200"
    mp:
      root: "A/California/7/2009"
      refs:
        NC_026431:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
    ns:
      root: "A/California/7/2009"
      refs:
        NC_026432:
          reference_strain: A/California/7/2009
          filter: "--min-date 2009 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
  h3n2:
    pb2:
      root: "A/HongKong/1/1968"
      refs:
        NC_007373:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pb1:
      root: "A/HongKong/1/1968"
      refs:
        NC_007372:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
    pa:
      root: "A/HongKong/1/1968"
      refs:
        NC_007371:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 1800 --subsample-max-sequences 200"
    np:
      root: "A/HongKong/1/1968"
      refs:
        NC_007369:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 1200 --subsample-max-sequences 200"
    mp:
      root: "A/HongKong/1/1968"
      refs:
        NC_007367:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
    ns:
      root: "A/HongKong/1/1968"
      refs:
        NC_007370:
          reference_strain: A/NewYork/392/2004
          filter: "--min-date 1968 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
  # all-b:
  #   pb2:
  #     root: "B/Brisbane/60/2008"
  #     refs:
  #       NC_007373:
  #         filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
  #   pb1:
  #     root: "B/Brisbane/60/2008"
  #     refs:
  #       NC_007372:
  #         filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 2200 --subsample-max-sequences 200"
  #   pa:
  #     root: "B/Brisbane/60/2008"
  #     refs:
  #       NC_007371:
  #         filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 1800 --subsample-max-sequences 200"
  #   np:
  #     root: "B/Brisbane/60/2008"
  #     refs:
  #       NC_007369:
  #         filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 1200 --subsample-max-sequences 200"
  #   m:
  #     root: "B/Brisbane/60/2008"
  #     refs:
  #       NC_007367:
  #         filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
  #   ns:
  #     root: "B/Brisbane/60/2008"
  #     refs:
  #       NC_007370:
  #         filter: "--min-date 1940 --probabilistic-sampling --group-by year region --min-length 800 --subsample-max-sequences 200"
