
inputs:
  metadata: "./ingest/results/everything/metadata.tsv"
  sequences: "./ingest/results/everything/{segment}.fasta"

lat-longs: "config/lat_longs.tsv"

select_strains:
  args: |
    --query n_segments==8
    --group-by host region year
    --probabilistic-sampling
    --min-date 2020-01-01
    --subsample-max-sequences 1500
  weights: 'profiles/all-influenza/weights.txt'
  
align:
  # This is dubious AF, but hopefully good enough to start with
  reference:
    'pb2': "nextclade/dataset_config/h3n2/pb2/reference.fasta"
    'pb1': "nextclade/dataset_config/h3n2/pb1/reference.fasta"
    'pa': "nextclade/dataset_config/h3n2/pa/reference.fasta"
    'ha': "nextclade/dataset_config/h3n2/ha/CY163680/reference.fasta"
    'np': "nextclade/dataset_config/h3n2/np/reference.fasta"
    'na': "nextclade/dataset_config/h3n2/na/EPI1857215/reference.fasta"
    'mp': "nextclade/dataset_config/h3n2/mp/reference.fasta"
    'ns': "nextclade/dataset_config/h3n2/ns/reference.fasta"
  genes:
    'pb2': ['PB2']
    'pb1': ['PB1', 'PB1-F2']
    'pa': ['PA', 'PA-X']
    'ha': ['SigPep', 'HA1', 'HA2']
    'np': ['NP']
    'na': ['NA']
    'mp': ['M1', 'M2']
    'ns': ['NEP', 'NS1']
  annotation:
    'pb2': "nextclade/dataset_config/h3n2/pb2/annotation.gff"
    'pb1': "nextclade/dataset_config/h3n2/pb1/annotation.gff"
    'pa': "nextclade/dataset_config/h3n2/pa/annotation.gff"
    'ha': "nextclade/dataset_config/h3n2/ha/CY163680/annotation.gff"
    'np': "nextclade/dataset_config/h3n2/np/annotation.gff"
    'na': "nextclade/dataset_config/h3n2/na/EPI1857215/annotation.gff"
    'mp': "nextclade/dataset_config/h3n2/mp/annotation.gff"
    'ns': "nextclade/dataset_config/h3n2/ns/annotation.gff"

tree:
  method: iqtree
  tree-builder-args: "'-ninit 10 -n 4 -czb -nt AUTO'"
  override_default_args: true

traits:
  columns:
    - region
    - host


# submission_date_field: date_submitted
# recency:
#   date_bins: [7, 30, 90]
#   date_bin_labels: ["last week", "last month", "last quarter"]
#   upper_bin_label: older

# builds:
#   h1n1pdm_2y:
#     lineage: h1n1pdm
#     reference: "config/h1n1pdm/{segment}/reference.fasta"
#     annotation: "config/h1n1pdm/{segment}/genemap.gff"
#     tree_exclude_sites: "config/h1n1pdm/{segment}/exclude-sites.txt"
#     clades: "config/h1n1pdm/ha/clades.tsv"
#     auspice_config: "config/h1n1pdm/auspice_config.json"
#     min_date: "2Y"
#     reference_min_date: "8Y"
#     include: "config/h1n1pdm/reference_strains.txt"
#     exclude: "config/h1n1pdm/outliers.txt"
#     vaccines: "config/h1n1pdm/vaccine.json"
#     enable_glycosylation: true
#     enable_lbi: true
#     enable_titer_models: true
#     titer_collections:
#       - name: cell_hi
#         data: "data/h1n1pdm/who_ferret_cell_hi_titers.tsv"
#     subsamples: &representative-subsampling-scheme
#       regions_except_europe:
#           filters: --query "(passage_category != 'egg') & (region != 'Europe') & (ha == True) & (na == True)" --group-by region year month --subsample-max-sequences 1800 --min-date {min_date} --exclude {exclude}
#           priorities: "titers"
#       europe:
#           filters: --query "(passage_category != 'egg') & (region == 'Europe') & (ha == True) & (na == True)" --group-by country year month --subsample-max-sequences 200 --min-date {min_date} --exclude {exclude}
#           priorities: "titers"
#       context:
#           filters: --query "(passage_category != 'egg')" --group-by region year --subsample-max-sequences 300 --max-date 2020-03-01 --min-date 2016-01-01 --exclude {exclude}
#       references:
#           filters: --query "(passage_category != 'egg') & (is_reference == True)" --min-date {reference_min_date}
#   h3n2_2y:
#     lineage: "h3n2"
#     reference: "config/h3n2/{segment}/reference.fasta"
#     annotation: "config/h3n2/{segment}/genemap.gff"
#     tree_exclude_sites: "config/h3n2/{segment}/exclude-sites.txt"
#     clades: "config/h3n2/ha/emerging_clades.tsv"
#     auspice_config: "config/h3n2/auspice_config_fitness.json"
#     vaccines: "config/h3n2/vaccine.json"
#     enable_glycosylation: true
#     enable_lbi: true
#     enable_forecasts: true
#     enable_titer_models: true
#     min_date: "2Y"
#     reference_min_date: "8Y"
#     include: "config/h3n2/reference_strains.txt"
#     exclude: "config/h3n2/outliers.txt"
#     titer_collections:
#       - name: cell_fra
#         data: "data/h3n2/who_ferret_cell_fra_titers.tsv"
#         prefix: cell_fra_
#     subsamples: *representative-subsampling-scheme
#   vic_2y:
#     lineage: vic
#     reference: "config/vic/{segment}/reference.fasta"
#     annotation: "config/vic/{segment}/genemap.gff"
#     tree_exclude_sites: "config/vic/{segment}/exclude-sites.txt"
#     clades: "config/vic/ha/clades.tsv"
#     auspice_config: "config/vic/auspice_config.json"
#     min_date: "2Y"
#     reference_min_date: "8Y"
#     include: "config/vic/reference_strains.txt"
#     exclude: "config/vic/outliers.txt"
#     vaccines: "config/vic/vaccine.json"
#     enable_glycosylation: true
#     enable_lbi: true
#     enable_titer_models: true
#     titer_collections:
#       - name: cell_hi
#         data: "data/vic/who_ferret_cell_hi_titers.tsv"
#     subsamples: *representative-subsampling-scheme

# fitness_model:
#   models:
#     - cTiter_x_cell_fra-ne_star
#     - ne_star-lbi
#   best_model: cTiter_x_cell_fra-ne_star
#   delta_months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
#   pivot_interval: 6
#   delta_pivots: 1
#   months_back_for_current_samples: 6
#   max_years_for_distances: 5
#   number_of_forecast_samples: 1
#   excluded_node_data_fields:
#     - aa_muts
#     - aa_sequences
#     - muts
#     - num_date_confidence
#     - sequence
